# Generated by Django 3.0.8 on 2021-10-02 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20211002_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.Payment'),
        ),
    ]
